### ISSUE TITLE
To-Do Feature List

### ISSUE THREAD

**Issue by Tsomoriri** [Aditya-Kaul/hybrid_ai_personalised_learning#2]
- [] Vocabulary, Higher Order Thinking skill metrics to lessons
- [] Caching support for LLM lesson generation request
- [] Multiple Chunking strategies for parsing huge documents
- [] Containerize the app
